### ISSUE TITLE
Add progression indicator to import module

### ISSUE THREAD

**Issue by LaChapeliere** [CRANE-toolbox/analysis-pipelines#24]

**Comment by riibeirogabriel** [comment]
This sounds like the bar progress on terminal?

**Comment by LaChapeliere** [comment]
Yup, or a percentage.
Two infos are needed: one that says "File x out y" when the command is excecuted on a folder rather than a single file + "x% of file read" for the current file. The second one might be problematic because we need to know how many lines are in the file first.

**Comment by riibeirogabriel** [comment]
Sounds good, please let me take a look.

**Comment by riibeirogabriel** [comment]
@LaChapeliere I have tried run `pip install -e .` in project root, but this error happens
![image](https://user-images.githubusercontent.com/33736256/98460438-2cbdca00-2183-11eb-9ff3-bebd3bf14015.png)

This also happens in your machine with current code in master?

**Comment by LaChapeliere** [comment]
> @LaChapeliere I have tried run `pip install -e .` in project root, but this error happens
> ![image](https://user-images.githubusercontent.com/33736256/98460438-2cbdca00-2183-11eb-9ff3-bebd3bf14015.png)
> 
> This also happens in your machine with current code in master?

Sorry, I was working on non-programming projects, took me some time to come back to this. No, I don't have this error, I suspect a Windows error since I see that's what you're using and I'm on Linux. Will look into it. @IanSaucy Is that a problem we've met before with Kelly's Windows env?

**Comment by IanSaucy** [comment]
So I think is due to how the path is being built [here](https://github.com/CRANE-toolbox/analysis-pipelines/blob/a142200d53d955d5313f69308011bc01e443329a/setup.py#L6). This method would work for most *nix systems but probably fails on windows since windows uses a `\` not a `/` for paths. 

We should change the method in the `setup.py` to use [`os.path.join`](https://docs.python.org/3/library/os.path.html#os.path.join). 

I think this should fix the issue but I have not tested.

**Comment by LaChapeliere** [comment]
@riibeirogabriel The fix has been merged to master and published on PyPi. Please tell me if you run into new problems :+1:

**Comment by riibeirogabriel** [comment]
@LaChapeliere Okay, thanks!
